# Generated by Django 2.2.4 on 2019-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='', max_length=50)),
                ('vendor_email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('mobileno', models.IntegerField()),
            ],
        ),
    ]
