# Generated by Django 2.2.4 on 2019-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField()),
                ('discription', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
