# Generated by Django 2.2.4 on 2019-09-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField()),
                ('suggesst', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='discription',
        ),
        migrations.AddField(
            model_name='package',
            name='dis',
            field=models.CharField(default='', max_length=50),
        ),
    ]
