# Generated by Django 2.2.4 on 2019-09-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_auto_20190923_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_email',
            new_name='vendor_password',
        ),
    ]
